### ISSUE TITLE
please help with images of 32 x 32 and more

### ISSUE THREAD

**Issue by hugocastalleda** [adafruit/Adafruit_CircuitPython_Pixel_Framebuf#5]
good night I would like you to help me to show images in 32 x 32 and 64 x 64 thanks

pixel_pin = board.D18
pixel_width = 32
pixel_height = 32

**Comment by jposada202020** [comment]
Hello @hugocastalleda . We do not use Github for support. You could use one of to options: Adafruit Discord in one of the help channels, people could help you there or the Adafruit support forums. Thanks :)
